source("R/src/server/graficos/grafico_series.R")
source("R/src/server/graficos/grafico_sazonalidade.R")
source("R/src/server/graficos/grafico_series_estac.R")
source("R/src/server/graficos/grafico_ACF.R")
source("R/src/server/graficos/comp_geo_vacinas.R")