source("./src/server/graficos/grafico_series.R")
source("./src/server/graficos/grafico_sazonalidade.R")
source("./src/server/graficos/grafico_series_estac.R")
source("./src/server/graficos/grafico_ACF.R")
source("./src/server/graficos/comp_geo.R")
source("./src/server/graficos/grafico_medidas_politicas.R")